# Generated by Django 4.2.1 on 2026-07-28 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(db_index=True, max_length=255)),
                ('periodo', models.CharField(db_index=True, max_length=255)),
                ('tipo', models.CharField(default='Capital', max_length=50)),
                ('datos_cuestionario', models.TextField()),
                ('fecha_creacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ultima_modificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
    ]
